name: observability

services:
  alloy:
    image: grafana/alloy:v1.20.0@sha256:f111cce835516c5f99166342be7038496b52ced16667be5a11e19258a3e4cd30
    restart: unless-stopped
    command:
      - run
      - /etc/alloy/config/config.alloy
    volumes:
      - ./config/alloy:/etc/alloy/config:ro
      - ${APPDATA}/alloy/data:/var/lib/alloy
      - ${APPDATA}/traefik/logs:/logs/traefik:ro
    networks:
      - docker_socket
      - monitoring

  loki:
    image: grafana/loki:3.7.8@sha256:1107dd5274e0ada47e42472b7a7e71f3b2a2fe878878108f3e2f9e51528f0193
    restart: unless-stopped
    command: -config.file=/etc/loki/config/loki-config.yaml
    volumes:
      - ./config/loki:/etc/loki/config:ro
      - ${APPDATA}/loki/data:/loki
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:13.2.2@sha256:ac461fb352abc50da10a51c7d02462e9c05488f11f53f14b3ad79a8145f638a0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${APPDATA}/grafana:/var/lib/grafana
    networks:
      - ingress
      - monitoring
    labels:
      # Unraid
      net.unraid.docker.webui: "https://grafana.${DOMAIN}"
      net.unraid.docker.shell: "sh"

      # Traefik
      traefik.enable: "true"
      traefik.docker.network: "ingress"
      traefik.http.routers.grafana.rule: "Host(`grafana.bakers.house`)"
      traefik.http.routers.grafana.entrypoints: "https"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"

networks:
  monitoring:
  docker_socket:
    name: docker_socket
    external: true
  ingress:
    name: ingress
    external: true
